[package]
name = "rust-template"
version = "0.1.0"
authors = ["Charles Macharia <machariacharleskariuki@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
num-traits = "0.2.8"
serde = "1.0.8"
serde_json = "1.0.79"
serde_derive = "1.0.136"
# lazy_static = "1.4.0"
# windows = "0.38.0"

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
